// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: service/v1/order.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//获取订单信息
type GetOrderInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId uint64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *GetOrderInfoReq) Reset() {
	*x = GetOrderInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoReq) ProtoMessage() {}

func (x *GetOrderInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoReq.ProtoReflect.Descriptor instead.
func (*GetOrderInfoReq) Descriptor() ([]byte, []int) {
	return file_service_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderInfoReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalAmount float32                    `protobuf:"fixed32,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Items       []*GetOrderInfoReply_Items `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetOrderInfoReply) Reset() {
	*x = GetOrderInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoReply) ProtoMessage() {}

func (x *GetOrderInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoReply.ProtoReflect.Descriptor instead.
func (*GetOrderInfoReply) Descriptor() ([]byte, []int) {
	return file_service_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderInfoReply) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetOrderInfoReply) GetItems() []*GetOrderInfoReply_Items {
	if x != nil {
		return x.Items
	}
	return nil
}

// 创建订单
type AddOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*AddOrderReq_Items `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *AddOrderReq) Reset() {
	*x = AddOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderReq) ProtoMessage() {}

func (x *AddOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderReq.ProtoReflect.Descriptor instead.
func (*AddOrderReq) Descriptor() ([]byte, []int) {
	return file_service_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *AddOrderReq) GetItems() []*AddOrderReq_Items {
	if x != nil {
		return x.Items
	}
	return nil
}

type AddOrderReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddOrderReply) Reset() {
	*x = AddOrderReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_order_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderReply) ProtoMessage() {}

func (x *AddOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_order_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderReply.ProtoReflect.Descriptor instead.
func (*AddOrderReply) Descriptor() ([]byte, []int) {
	return file_service_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *AddOrderReply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetOrderInfoReply_Items struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Desc  string  `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	Price float32 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *GetOrderInfoReply_Items) Reset() {
	*x = GetOrderInfoReply_Items{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_order_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderInfoReply_Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoReply_Items) ProtoMessage() {}

func (x *GetOrderInfoReply_Items) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_order_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoReply_Items.ProtoReflect.Descriptor instead.
func (*GetOrderInfoReply_Items) Descriptor() ([]byte, []int) {
	return file_service_v1_order_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetOrderInfoReply_Items) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GetOrderInfoReply_Items) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type AddOrderReq_Items struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductCode     string   `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	IngredientCodes []string `protobuf:"bytes,2,rep,name=ingredient_codes,json=ingredientCodes,proto3" json:"ingredient_codes,omitempty"`
}

func (x *AddOrderReq_Items) Reset() {
	*x = AddOrderReq_Items{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_order_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOrderReq_Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderReq_Items) ProtoMessage() {}

func (x *AddOrderReq_Items) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_order_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderReq_Items.ProtoReflect.Descriptor instead.
func (*AddOrderReq_Items) Descriptor() ([]byte, []int) {
	return file_service_v1_order_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AddOrderReq_Items) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *AddOrderReq_Items) GetIngredientCodes() []string {
	if x != nil {
		return x.IngredientCodes
	}
	return nil
}

var File_service_v1_order_proto protoreflect.FileDescriptor

var file_service_v1_order_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x2c, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0xaa, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x21,
	0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x3f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x1a, 0x31, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x1a, 0x55, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x29, 0x0a, 0x10,
	0x69, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x27, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0xa8, 0x01, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x53, 0x0a, 0x09, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x4a, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x64, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64,
	0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x19, 0x5a, 0x17, 0x61,
	0x70, 0x69, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_v1_order_proto_rawDescOnce sync.Once
	file_service_v1_order_proto_rawDescData = file_service_v1_order_proto_rawDesc
)

func file_service_v1_order_proto_rawDescGZIP() []byte {
	file_service_v1_order_proto_rawDescOnce.Do(func() {
		file_service_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_v1_order_proto_rawDescData)
	})
	return file_service_v1_order_proto_rawDescData
}

var file_service_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_v1_order_proto_goTypes = []interface{}{
	(*GetOrderInfoReq)(nil),         // 0: order.service.v1.GetOrderInfoReq
	(*GetOrderInfoReply)(nil),       // 1: order.service.v1.GetOrderInfoReply
	(*AddOrderReq)(nil),             // 2: order.service.v1.AddOrderReq
	(*AddOrderReply)(nil),           // 3: order.service.v1.AddOrderReply
	(*GetOrderInfoReply_Items)(nil), // 4: order.service.v1.GetOrderInfoReply.Items
	(*AddOrderReq_Items)(nil),       // 5: order.service.v1.AddOrderReq.Items
}
var file_service_v1_order_proto_depIdxs = []int32{
	4, // 0: order.service.v1.GetOrderInfoReply.items:type_name -> order.service.v1.GetOrderInfoReply.Items
	5, // 1: order.service.v1.AddOrderReq.items:type_name -> order.service.v1.AddOrderReq.Items
	0, // 2: order.service.v1.Order.OrderInfo:input_type -> order.service.v1.GetOrderInfoReq
	2, // 3: order.service.v1.Order.AddOrder:input_type -> order.service.v1.AddOrderReq
	1, // 4: order.service.v1.Order.OrderInfo:output_type -> order.service.v1.GetOrderInfoReply
	3, // 5: order.service.v1.Order.AddOrder:output_type -> order.service.v1.AddOrderReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_v1_order_proto_init() }
func file_service_v1_order_proto_init() {
	if File_service_v1_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_v1_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_order_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOrderReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_order_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderInfoReply_Items); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_order_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOrderReq_Items); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_v1_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_v1_order_proto_goTypes,
		DependencyIndexes: file_service_v1_order_proto_depIdxs,
		MessageInfos:      file_service_v1_order_proto_msgTypes,
	}.Build()
	File_service_v1_order_proto = out.File
	file_service_v1_order_proto_rawDesc = nil
	file_service_v1_order_proto_goTypes = nil
	file_service_v1_order_proto_depIdxs = nil
}
