// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"google.golang.org/grpc"
	"log"
	"rshop/app/product/service/internal/biz"
	"rshop/app/product/service/internal/conf"
	"rshop/app/product/service/internal/dao"
	"rshop/app/product/service/internal/server"
	"rshop/app/product/service/internal/service"
)

// Injectors from wire.go:

//initApp init kratos application.
func initApp(logger *log.Logger, data *conf.Data, confServer *conf.Server) *grpc.Server {
	db := dao.NewDB(data)
	daoDao := dao.NewDao(db, logger)
	productRepo := dao.NewProductRepo(daoDao, logger)
	productUserCase := biz.NewProductUserCase(productRepo, logger)
	productService := service.NewProductService(productUserCase, logger)
	grpcServer := server.NewGRPCServer(confServer, productService)
	return grpcServer
}
